name: Check CS

on:
    pull_request_target:

jobs:
    build:
        env:
            COMPOSER_ROOT_VERSION: dev-master

        runs-on: ubuntu-latest
        name: Check code style
        steps:
            -   uses: actions/checkout@v3
                with:
                    fetch-depth: 10

            -   name: Install PHP
                uses: shivammathur/setup-php@v2
                with:
                    coverage: none
                    php-version: "8.0"
                    tools: cs2pr

            - name: Install Composer dependencies
              uses: ramsey/composer-install@v2
              with:
                  # Bust the cache at least once a month - output format: YYYY-MM.
                  custom-cache-suffix: $(date -u "+%Y-%m")

            -   name: Run git-phpcs
                run: composer cscheck -- --report=checkstyle | cs2pr
