name: Tests
on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php_version:
                    - '7.4'
                    - '8.0'
                composer_flags:
                    - ''
                    - '-o'

        name: 'PHP ${{ matrix.php_version }} (composer_flags: "${{ matrix.composer_flags }}")'
        steps:
            - uses: actions/checkout@v2
            - name: Setup PHP with pecl extension
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php_version }}
                  extensions: :opcache
            - run: composer install ${{ matrix.composer_flags }}
            - run: vendor/bin/phpunit
              if: ${{ matrix.php_version != '8.0' }}
            - run: vendor/bin/phpunit --coverage-clover coverage.xml
              if: ${{ matrix.php_version == '8.0' }}
              env:
                  XDEBUG_MODE: coverage
            - name: Upload coverage to Codecov
              if: ${{ matrix.php_version == '8.0' }}
              uses: codecov/codecov-action@v1
              with:
                  file: ./coverage.xml
