name: Tests
on:
    push:
        branches:
            - "master"
    pull_request_target:

jobs:
    tests:
        permissions:
            id-token: write
            contents: read

        env:
            COMPOSER_ROOT_VERSION: dev-master

        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os:
                    - ubuntu-latest
                    - windows-latest

                php_version:
                    - '8.1'
                    - '8.2'
                    - '8.3'
                    - '8.4'

                composer_flags:
                    - ''
                    - '-o'

        name: 'PHP ${{ matrix.php_version }} (os: ${{ matrix.os }} composer_flags: "${{ matrix.composer_flags }}")'
        steps:
            - uses: actions/checkout@v4
            - name: Setup PHP with pecl extension
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php_version }}
                  extensions: :opcache, pcov

            - run: composer remove --dev --no-update roave/better-reflection
              if: ${{ matrix.php_version == '8.4' }} # Temporary: better reflection does not support 8.4

            - name: Install Composer dependencies
              uses: ramsey/composer-install@v3
              with:
                  composer-options: ${{ matrix.composer_flags }}

            - name: Install Composer dependencies (tests)
              run: php tests/install-deps.php
              env:
                  COMPOSER_FLAGS: ${{ matrix.composer_flags }}

            - run: vendor/bin/phpunit
              if: ${{ matrix.php_version != '8.3' }}
            - run: vendor/bin/phpunit --coverage-clover coverage.xml --log-junit junit.xml
              if: ${{ matrix.php_version == '8.3' }}
              env:
                  XDEBUG_MODE: coverage

            - name: Upload test results to Codecov
              if: ${{ !cancelled() && matrix.php_version == '8.3' }}
              uses: codecov/test-results-action@v1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}

            - name: Upload coverage to Codecov
              if: ${{ !cancelled() && matrix.php_version == '8.3' }}
              uses: codecov/codecov-action@v4
              with:
                  use_oidc: true
                  file: ./coverage.xml

    phpdocumentor_tests:
        permissions:
            id-token: write
            contents: read

        env:
            COMPOSER_ROOT_VERSION: dev-master

        runs-on: ubuntu-latest
        strategy:
            matrix:
                phpdocumentor_version:
                    - '4.0'
                    - '5.0'

                composer_flags:
                    - ''
                    - '-o'

        name: 'phpDocumentor ${{ matrix.phpdocumentor_version }} (on PHP 8.3 composer_flags: "${{ matrix.composer_flags }}")'
        steps:
            - uses: actions/checkout@v4
            - name: Setup PHP with pecl extension
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'
                  extensions: :opcache, pcov

            - name: Require phpDocumentor ${{ matrix.phpdocumentor_version }}
              run: composer require --dev --no-update -n "phpdocumentor/reflection:^${{ matrix.phpdocumentor_version }}"

            - name: Install Composer dependencies
              uses: ramsey/composer-install@v3
              with:
                  composer-options: ${{ matrix.composer_flags }}
                  dependency-versions: highest

            - name: Install Composer dependencies (tests)
              run: php tests/install-deps.php
              env:
                  COMPOSER_FLAGS: ${{ matrix.composer_flags }}

            - run: vendor/bin/phpunit --coverage-clover coverage.xml --log-junit junit.xml
              env:
                  XDEBUG_MODE: coverage

            - name: Upload test results to Codecov
              if: ${{ !cancelled() }}
              uses: codecov/test-results-action@v1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}

            - name: Upload coverage to Codecov
              if: ${{ !cancelled() }}
              uses: codecov/codecov-action@v4
              with:
                  use_oidc: true
                  file: ./coverage.xml
